print ("  VV VV VV                 VV VV VV    II II II        PP PP PP PP PP                              ")
print ("      VV                     VV           II              PP         PP                             ")
print ("       VV                   VV            II              PP          PP                        ")
print ("        VV                 VV             II              PP           PP                         ")
print ("         VV               VV              II              PP           PP                     ")
print ("          VV             VV               II              PP           PP                 ")
print ("           VV           VV                II              PP         PP                   ")
print ("            VV         VV                 II              PP PP PP PP                     ")
print ("             VV       VV                  II              PP                                      ")
print ("              VV     VV                   II              PP                       ")
print ("               VV   VV                    II              PP                        ")
print ("                VV VV                     II              PP                       ")
print ("                 VVV                   II II II         PPPPPP                           ")